hook.Add( "InitPostEntity", "fpsbooster", function()
	 	RunConsoleCommand("gmod_mcore_test", "1")
	 	RunConsoleCommand("mat_queue_mode", "-1")
	 	RunConsoleCommand("cl_threaded_bone_setup", "1")
	 	RunConsoleCommand("cl_threaded_client_leaf_system", "1")
	 	RunConsoleCommand("r_threaded_client_shadow_manager", "1")
	 	RunConsoleCommand("r_threaded_particles", "1")
	 	RunConsoleCommand("r_threaded_renderables", "1")
	 	RunConsoleCommand("r_queued_ropes", "1")
	 	RunConsoleCommand("studio_queue_mode", "1")
	 	RunConsoleCommand("r_fastzreject", "-1")
	 	RunConsoleCommand("mat_shadowstate", "0")
	 	RunConsoleCommand("r_shadowmaxrendered", "0")
	 	RunConsoleCommand("r_shadowrendertotexture", "0")
	 	RunConsoleCommand("r_shadows", "0")
	 	RunConsoleCommand("r_3dsky", "0")
	 	RunConsoleCommand("cl_playerspraydisable", "1")
	 	RunConsoleCommand("r_spray_lifetime", "0")
	 	RunConsoleCommand("cl_phys_props_enable", "0")
	 	RunConsoleCommand("cl_phys_props_max", "0")
	 	RunConsoleCommand("props_break_max_pieces", "0")
	 	RunConsoleCommand("r_propsmaxdist", "1")
	 	RunConsoleCommand("violence_agibs", "0")
	 	RunConsoleCommand("violence_hgibs", "0")

	 	hook.Remove("RenderScreenspaceEffects", "RenderColorModify")
 		hook.Remove("RenderScreenspaceEffects", "RenderBloom")
 		hook.Remove("RenderScreenspaceEffects", "RenderToyTown")
 		hook.Remove("RenderScreenspaceEffects", "RenderTexturize")
 		hook.Remove("RenderScreenspaceEffects", "RenderSunbeams")
 		hook.Remove("RenderScreenspaceEffects", "RenderSobel")
 		hook.Remove("RenderScreenspaceEffects", "RenderSharpen")
 		hook.Remove("RenderScreenspaceEffects", "RenderMaterialOverlay")
 		hook.Remove("RenderScreenspaceEffects", "RenderMotionBlur")
 		hook.Remove("RenderScene", "RenderStereoscopy")
 		hook.Remove("RenderScene", "RenderSuperDoF")
 		hook.Remove("GUIMousePressed", "SuperDOFMouseDown")
 		hook.Remove("GUIMouseReleased", "SuperDOFMouseUp")
 		hook.Remove("PreventScreenClicks", "SuperDOFPreventClicks")
 		hook.Remove("PostRender", "RenderFrameBlend")
 		hook.Remove("PreRender", "PreRenderFrameBlend")
 		hook.Remove("Think", "DOFThink")
 		hook.Remove("RenderScreenspaceEffects", "RenderBokeh")
 		hook.Remove("NeedsDepthPass", "NeedsDepthPass_Bokeh")
 		hook.Remove("PostDrawEffects", "RenderWidgets")
 		hook.Remove("PostDrawEffects", "RenderHalos")
end)
hook.Add("OnEntityCreated","WidgetInit",function(ent)
	if ent:IsWidget() then
		hook.Add( "PlayerTick", "TickWidgets", function( pl, mv ) widgets.PlayerTick( pl, mv ) end ) 
		hook.Remove("OnEntityCreated","WidgetInit")
	end
end)